import 'modern-css-reset';
import '@/styles/global/globals.css';

import type { Metadata } from 'next';
// eslint-disable-next-line camelcase
import { Noto_Sans_JP } from 'next/font/google';

const inter = Noto_Sans_JP({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ja">
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
